- hosts: workstation
  become: yes
  roles:
    - {role: osp-servers, osp_server: "{{ osp_servers['frontend'] }}"}
    - {role: osp-servers, osp_server: "{{ osp_servers['app1'] }}"}
    - {role: osp-servers, osp_server: "{{ osp_servers['app2'] }}"}
    - {role: osp-servers, osp_server: "{{ osp_servers['db'] }}"}
