---
# tasks file for app-tier

- name: Install tomcat
  yum:
    name: tomcat
    state: latest

- name: Enable tomcat at boot
  service:
    name: tomcat
    enabled: yes

- name: Create tomcat default web directory
  file:
    path: "{{ tomcat_web_root }}"
    state: directory

- name: Copy static index.html to tomat webroot
  template:
    src: ../templates/index.html.j2
    dest: "{{ tomcat_web_root }}/index.html"
    mode: 0644

- name: Restart tomcat
  service:
    name: tomcat
    state: restarted
